name: publish

on:
  release:
    types: [published]

jobs:
  build:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # See https://github.com/actions/virtual-environments/issues/2577#issuecomment-845126269
      - name: Blocked mirror workaround
        run: echo "1.1.1.1 invisible-mirror.net" | sudo tee -a /etc/hosts

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ubuntu-latest-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ubuntu-latest-gradle-
      - uses: actions/cache@v2
        with:
          path: |
            dl
            ~/.buildroot-ccache
          key: ubuntu-latest-buildroot-${{ hashFiles('.config') }}
          restore-keys: ubuntu-latest-buildroot-
      - name: Build with Gradle
        run: ./gradlew -Psemver='${{ github.event.release.tag_name }}' build
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_KEY: ${{ secrets.GPR_KEY }}

      - name: Add Artifacts to Github Release
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./build/libs/*.jar"]'

      - name: Publish to Github Packages
        run: gradle -Psemver='${{ github.event.release.tag_name }}' publish
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_KEY: ${{ secrets.GPR_KEY }}
          GITHUB_MAVEN_URL: 'https://maven.pkg.github.com/${{ github.repository }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
